let ENGINE_VERSIONS,normalizeAssessment,buildResult,profileCopy,formatCurrency;

const rawKey='escapeplan-assessment-v1',assessmentKey='escapeplan_assessment_v2',resultKey='escapeplan_result_v2',legacyStateKey='escapeplan_assessment_v2';
const page=location.pathname.split('/').filter(Boolean)[0];
const set=(id,value)=>{const node=document.getElementById(id);if(node)node.textContent=value??''};
const bandLabel={ready_to_test:'Ready to test',building_readiness:'Building readiness',needs_foundation:'Needs foundation'};
const brand=document.querySelector('.cv-brand');if(brand){brand.removeAttribute('href');brand.setAttribute('role','img');brand.setAttribute('aria-label','EscapePlan');brand.tabIndex=-1}
const narratorUser=record=>({employment:record.canonical_assessment.employment_status,motivation:record.canonical_assessment.primary_motivation,capital_band:record.raw_answers.capital?.[0]||null,hours_daily:record.canonical_assessment.available_hours_daily,environment:record.canonical_assessment.preferred_business_environment,strengths:record.canonical_assessment.strengths,archetype:record.result.profile_archetype.label,top_match:record.result.top_business.name});
async function requestNarration(record,event,extra,apply){const started=performance.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),650);try{const response=await fetch('/api/narrate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event,user:narratorUser(record),fact_tokens:extra.fact_tokens||[],allowed_claims:extra.allowed_claims||[],hidden_names:[],allowed_numbers:[],fallback_reaction:extra.fallback_reaction||'',fallback_insight:extra.fallback_insight||'',fallback_curiosity:extra.fallback_curiosity||''}),signal:controller.signal});clearTimeout(timer);if(!response.ok)return;const data=await response.json(),core=await import('/shared/narrator-core.mjs'),checked=core.validateNarration(data.narration,{hidden_names:extra.hidden_names||[],allowed_numbers:[]});if(data.meta?.narrator_mode==='AI'&&performance.now()-started<600&&checked.ok)apply(checked.value);document.dispatchEvent(new CustomEvent('escapeplan:narration',{detail:checked.ok?data.meta:{narrator_mode:'DETERMINISTIC_FALLBACK'}}))}catch{document.dispatchEvent(new CustomEvent('escapeplan:narration',{detail:{narrator_mode:'DETERMINISTIC_FALLBACK'}}))}}

function readRaw(){for(const storage of [localStorage,sessionStorage]){try{const value=JSON.parse(storage.getItem(rawKey)||'null');if(value?.answerText)return value}catch(_){}}return null;}
async function sha256(value){const bytes=new TextEncoder().encode(value),digest=await crypto.subtle.digest('SHA-256',bytes);return `sha256:${[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}`;}
async function calculate(){
  const raw=readRaw();if(!raw)throw new Error('ASSESSMENT_MISSING');
  const assessment=normalizeAssessment(raw,'local-assessment-v2');
  const response=await fetch('/data/BUSINESS_MODELS_SEED_V2.json');if(!response.ok)throw new Error('DATASET_UNAVAILABLE');
  const data=await response.json();if(data.dataset_version!==ENGINE_VERSIONS.business_dataset_version)throw new Error('DATASET_VERSION_MISMATCH');
  const result=buildResult(assessment,data.models);
  result.engine.input_hash=await sha256(JSON.stringify(assessment));result.engine.engine_configuration_hash=await sha256(JSON.stringify(ENGINE_VERSIONS));
  result.generated_at=new Date().toISOString();const record={record_version:'escapeplan-result-state-v2',saved_at:result.generated_at,versions:ENGINE_VERSIONS,raw_answers:raw.answerText,canonical_assessment:assessment,result};
  const assessmentRecord={record_version:'escapeplan-assessment-state-v2',saved_at:result.generated_at,versions:ENGINE_VERSIONS,raw_answers:raw.answerText,canonical_assessment:assessment};
  localStorage.setItem(assessmentKey,JSON.stringify(assessmentRecord));sessionStorage.setItem(assessmentKey,JSON.stringify(assessmentRecord));localStorage.setItem(resultKey,JSON.stringify(record));sessionStorage.setItem(resultKey,JSON.stringify(record));return record;
}
async function loadRecord(){for(const storage of [localStorage,sessionStorage]){for(const key of [resultKey,legacyStateKey]){try{const value=JSON.parse(storage.getItem(key)||'null');if(value?.versions?.scoring_model_version===ENGINE_VERSIONS.scoring_model_version&&value?.versions?.quiz_schema_version===ENGINE_VERSIONS.quiz_schema_version&&value?.result?.top_business)return value}catch(_){}}}return calculate();}
function failure(error){document.body.innerHTML='<main class="cv-error"><h1>We couldn’t finish your match just now.</h1><p>Your answers are still saved.</p><button type="button" id="retry-analysis">Retry Analysis</button><button type="button" id="restart-assessment">Start Again</button></main>';document.getElementById('retry-analysis').addEventListener('click',()=>{localStorage.removeItem(resultKey);sessionStorage.removeItem(resultKey);location.href='/analysis-v2/code'});document.getElementById('restart-assessment').addEventListener('click',()=>{[rawKey,assessmentKey,resultKey].forEach(key=>{localStorage.removeItem(key);sessionStorage.removeItem(key)});location.href='/assessment/code'});console.error('EscapePlan scoring failed:',error.message);}
function reasons(result){return result.top_business.reasons.map(x=>x.label);}

function renderAnalysis(record){
  const {result,canonical_assessment:a}=record;const topCategories=[...new Set(result.ranked_businesses.slice(0,12).map(x=>x.category))];
  document.getElementById('category-nodes').innerHTML=topCategories.map((name,index)=>`<span style="--n:${index}">${name.replace(/-/g,' ')}</span>`).join('');
  const signals=[`Capital fit: ${Math.round(result.top_business.factor_scores.capital)}%`,`Time fit: ${Math.round(result.top_business.factor_scores.time)}%`,`Strengths fit: ${Math.round(result.top_business.factor_scores.skills)}%`,`Operating style: ${Math.round(result.top_business.factor_scores.operating_style)}%`,`${result.ranked_businesses.length} eligible models compared`];
  document.getElementById('signal-list').innerHTML=signals.map((signal,index)=>`<li style="--delay:${index}"><span>${signal}</span><b>✓</b></li>`).join('');
  document.getElementById('analysis-ready').hidden=false;
}
function renderDNA(record){
  const {result,canonical_assessment:a}=record;set('profile-title',result.profile_archetype.label);set('profile-copy',profileCopy(a,result));
  const qualitativeFill={High:85,Moderate:60,Low:35};document.getElementById('dna-bars').innerHTML=result.business_dna.slice(0,4).map(x=>`<div style="--fill:${Math.round(x.value??qualitativeFill[x.band])}%"><span>${x.label.toUpperCase()}<b>${x.band}</b></span><i><em></em></i></div>`).join('');
  const fallback=profileCopy(a,result);set('standout-title',fallback);document.getElementById('fit-signals').innerHTML=reasons(result).slice(0,3).map(reason=>`<li>${reason}<b>✓</b></li>`).join('');requestNarration(record,'profile_reveal',{fact_tokens:result.business_dna.filter(x=>x.band==='High').map(x=>`DNA_${x.id.toUpperCase()}`),allowed_claims:['profile_archetype','business_dna'],fallback_insight:fallback},copy=>{if(copy.insight)set('profile-copy',copy.insight)});
}
function renderMatch(record){
  const {result}=record,top=result.top_business;set('match-name',top.name);document.querySelector('.score-note').textContent=`${Math.round(top.profile_match_score)}% Profile Match reflects alignment with your answers—not probability of success.`;
  document.getElementById('match-reasons').innerHTML=reasons(result).map(reason=>`<li><b>✓</b><span>${reason}</span></li>`).join('');
  set('curiosity-line',result.alternative_teasers[0]?.label||'Your strongest path is only one way to fit your answers.');
  const routes=[...document.querySelectorAll('.map-route')];routes[0].querySelector('strong').textContent=top.name;routes[0].querySelector('small').textContent=`${Math.round(top.profile_match_score)}% Profile Match`;
  result.alternative_teasers.forEach((teaser,index)=>{const route=routes[index+1];if(!route)return;route.querySelector('b').textContent=`#${teaser.rank}`;route.querySelector('small').textContent=`${Math.round(teaser.profile_match_score)}% · ${teaser.label}`;});
  routes.slice(result.alternative_teasers.length+1).forEach(route=>route.hidden=true);
  const poor=document.querySelector('.poor-routes');poor.innerHTML=result.avoid_models.map(()=>'<span>Poor fit ×</span>').join('');poor.setAttribute('aria-label',`${result.avoid_models.length} explainable poor-fit routes`);
  requestNarration(record,'match_reveal',{fact_tokens:top.reasons.map(x=>`TOP_FACTOR_${x.factor.toUpperCase()}`),allowed_claims:['top_match_identity','top_match_fit_reasons'],fallback_insight:reasons(result)[0]||'',hidden_names:result.alternative_teasers.map(x=>result.ranked_businesses.find(b=>b.business_model_id===x.business_model_id)?.name).filter(Boolean)},copy=>{if(copy.insight){const first=document.querySelector('#match-reasons li span');if(first)first.textContent=copy.insight}});
  requestNarration(record,'alternative_teaser',{fact_tokens:[`ALTERNATIVE_${(result.alternative_teasers[0]?.kind||'strong_alternative').toUpperCase()}`],allowed_claims:['alternative_comparison_role'],fallback_curiosity:result.alternative_teasers[0]?.label||'',hidden_names:result.alternative_teasers.map(x=>result.ranked_businesses.find(b=>b.business_model_id===x.business_model_id)?.name).filter(Boolean)},copy=>{if(copy.curiosity)set('curiosity-line',copy.curiosity)});
}
function renderPaywall(record){
  const {result,canonical_assessment:a,raw_answers:raw}=record,capital=raw.capital?.[0]||formatCurrency(a.money.safe_risk_capital_minor);
  set('capital-value',capital);set('capital-intro',`You said you could test with ${capital}. Compare the routes before you commit it.`);
  const motivation=raw.motivation?.[0],tradeoff=raw.tradeoff?.[0],env=raw.environment?.[0];let headline='Compare the paths before you spend the bigger money.';
  if(motivation==='I want out of my job eventually')headline='Before you leave your salary behind, compare the paths that can start beside it.';else if(raw.capital?.[0]==='Under ₹25K')headline='You don’t have money to waste testing the wrong model.';else if(['₹3L–₹7L','₹7L+'].includes(raw.capital?.[0]))headline=`Before you put ${capital} behind one idea, compare the alternatives.`;else if(tradeoff==='Money sooner')headline='Compare the paths by speed before you bet on one.';else if(env==='Sell or build through the internet')headline='Compare the digital paths before you commit to one.';set('paywall-headline',headline);
  const teaserQuestions=result.alternative_teasers.map(teaser=>teaser.label);while(teaserQuestions.length<3)teaserQuestions.push('Which strong alternative fits your answers differently?');const questions=[...teaserQuestions.slice(0,3),'What should you NOT start right now?'];document.querySelectorAll('.question-locks strong').forEach((node,index)=>node.textContent=questions[index]);
  const avoidCount=result.avoid_models.length;const avoidNode=document.querySelector('.question-locks article:last-child span');if(avoidNode)avoidNode.textContent=`${avoidCount} explainable poor-fit ${avoidCount===1?'business':'businesses'}`;
  const outcomes=[`${result.ranked_businesses.length} eligible paths`,'Your money plan',`${avoidCount} poor-fit ${avoidCount===1?'business':'businesses'}`,'Your first 30 days'];document.querySelectorAll('.unlock-outcomes b').forEach((node,index)=>node.textContent=outcomes[index]);
  const moneyCopy=document.querySelector('.unlock-outcomes p:nth-child(2) span');if(moneyCopy)moneyCopy.textContent=result.financial_preview.message;
  const preview=document.querySelector('.price-panel .cv-button');if(preview)preview.innerHTML='Preview the ₹199 Unlock <span aria-hidden="true">→</span>';const trust=document.querySelector('.trust-line');if(trust)trust.innerHTML='<span>No charge in preview</span><span>Instant access shown</span><span>No subscription</span>';
  requestNarration(record,'paywall_personalization',{fact_tokens:[`AVOID_COUNT_${avoidCount}`,result.alternative_teasers[0]?`ALTERNATIVE_${result.alternative_teasers[0].kind.toUpperCase()}`:'NO_MATERIAL_ALTERNATIVE'],allowed_claims:['motivation','employment','capital_band','top_match_exists','alternative_comparison_role','avoid_count'],fallback_reaction:headline,fallback_insight:`Your #1 fits you well, but ${result.alternative_teasers.length?'another route deserves comparison':'the trade-offs still deserve comparison'}.`,hidden_names:result.alternative_teasers.map(x=>result.ranked_businesses.find(b=>b.business_model_id===x.business_model_id)?.name).filter(Boolean)},copy=>{if(copy.reaction)set('paywall-headline',copy.reaction);if(copy.insight)set('capital-intro',copy.insight)});
}
function renderCheckout(record){const routes=[...document.querySelectorAll('.unlock-map .map-route')];record.result.ranked_businesses.slice(0,4).forEach((business,index)=>{const route=routes[index];if(!route)return;route.querySelector('b').textContent=`#${business.rank}`;route.querySelector('.locked-name').textContent=business.name;route.querySelector('.locked-name').dataset.computed='true';const score=document.createElement('small');score.textContent=`${Math.round(business.profile_match_score)}% Profile Match`;route.querySelector('article').appendChild(score);});}

(async()=>{try{({ENGINE_VERSIONS,normalizeAssessment,buildResult,profileCopy,formatCurrency}=await import('/shared/escapeplan-result-engine.mjs'));const record=page==='analysis-v2'?await calculate():await loadRecord();if(page==='analysis-v2')renderAnalysis(record);if(page==='result-v2')renderDNA(record);if(page==='match-v2')renderMatch(record);if(page==='unlock-v2')renderPaywall(record);if(page==='checkout_unlock_success_mobile')renderCheckout(record);}catch(error){failure(error);}})();
