import {readFileSync,writeFileSync} from 'node:fs';import{resolve}from'node:path';import{scoreV2,readiness}from'./match_engine_v2.mjs';import{scoreV1}from'./match_engine_v1.mjs';
const root=resolve(import.meta.dirname,'..'),load=n=>JSON.parse(readFileSync(resolve(root,'data',n)));const models=load('BUSINESS_MODELS_SEED_V2.json').models,qa=load('QA_PERSONAS.json').personas,reg=load('REGRESSION_PERSONAS.json').personas;
const rank=p=>models.map(m=>({id:m.business_model_id,category:m.category,...scoreV2(p,m)})).filter(x=>!x.excluded).sort((a,b)=>b.total-a.total||a.id.localeCompare(b.id));
const baseline={};for(const p of qa){const r=rank(p);baseline[p.assessment_id]={top5:r.slice(0,5).map(x=>({id:x.id,score:x.total,state:x.capital_state})),excluded:50-r.length,readiness:readiness(p)};}
let pass=0,fail=[];for(const x of reg){const r=rank(x.assessment),ids=r.map(y=>y.id),e=x.expectations;let ok=true;for(const id of e.top5_must_include??[])if(!ids.slice(0,5).includes(id))ok=false;for(const id of e.top10_must_exclude??[])if(ids.slice(0,10).includes(id))ok=false;if(e.top5_category_must_include&&!r.slice(0,5).some(y=>e.top5_category_must_include.includes(y.category)))ok=false;if(e.top10_must_not_be_all_online&&r.slice(0,10).every(y=>models.find(m=>m.business_model_id===y.id).online_offline_type==='online'))ok=false;if(ok)pass++;else fail.push({persona_id:x.persona_id,top5:r.slice(0,5).map(y=>y.id)});}
const employ=['student','full_time_job','part_time_job','ready_full_time','existing_business','unemployed'],envs=['online','offline','hybrid','no_preference'],strengths=[['none_identified'],['technology'],['sales'],['operations'],['creative','sales'],['product_sourcing','operations']],caps=[0,20000,100000,500000,2000000,10000000],hours=[1,2,4,8,12],risks=[1,2,3,4,5],targets=[20000,50000,100000,300000,1000000];
const pick=(a,i,s)=>a[(i*37+s*13+Math.floor(i/a.length))%a.length],template=structuredClone(qa[0]),stress=[];for(let i=0;i<80;i++){const p=structuredClone(template),cap=pick(caps,i,1);p.assessment_id=`stress-${String(i+1).padStart(3,'0')}`;p.employment_status=pick(employ,i,2);p.preferred_business_environment=pick(envs,i,3);p.strengths=pick(strengths,i,4);p.available_hours_daily=pick(hours,i,5);p.risk_tolerance=pick(risks,i,6);p.primary_motivation=pick(['extra_income','leave_job','financial_independence','build_asset','flexibility','exploration'],i,7);p.money.available_capital_minor=cap*100;p.money.safe_risk_capital_minor=Math.round(cap*pick([.2,.3,.4,.5,.6],i,8)*100);p.money.monthly_income_target_minor=pick(targets,i,9)*100;p.time_to_first_income_requirement=pick(['30_days','3_months','6_months','12_months','long_term'],i,10);p.savings_runway_months=pick([0,2,6,12,24],i,11);if(p.preferred_business_environment==='offline')Object.assign(p.operational_preferences,{customer_interaction_tolerance:5,staff_management_tolerance:4,inventory_tolerance:4,content_creation_tolerance:1,computer_work_tolerance:1,system_building_preference:2});else if(p.preferred_business_environment==='hybrid')Object.assign(p.operational_preferences,{customer_interaction_tolerance:4,staff_management_tolerance:3,inventory_tolerance:3,content_creation_tolerance:3,computer_work_tolerance:3,system_building_preference:3});else if(p.preferred_business_environment==='no_preference')Object.assign(p.operational_preferences,{customer_interaction_tolerance:3,staff_management_tolerance:3,inventory_tolerance:3,content_creation_tolerance:3,computer_work_tolerance:3,system_building_preference:3});stress.push(p)}
const allScores=[],oldScores=[],winner={},top3={},avoided={},exclusions=[];for(const p of stress){const r=rank(p);exclusions.push(50-r.length);if(r[0])winner[r[0].id]=(winner[r[0].id]||0)+1;for(const x of r.slice(0,3))top3[x.id]=(top3[x.id]||0)+1;for(const x of r)allScores.push(x.total);for(const m of models){const old=scoreV1(p,m);if(!old.excluded)oldScores.push(old.total);const x=r.find(y=>y.id===m.business_model_id);if(!x||x.total<50)avoided[m.business_model_id]=(avoided[m.business_model_id]||0)+1}}
allScores.sort((a,b)=>a-b);const pct=q=>allScores[Math.floor((allScores.length-1)*q)]??null,avg=allScores.reduce((a,b)=>a+b,0)/Math.max(1,allScores.length),bands={};for(const x of allScores){const b=x>=90?'90_100':x>=80?'80_89':x>=70?'70_79':x>=60?'60_69':x>=50?'50_59':'below_50';bands[b]=(bands[b]||0)+1}
oldScores.sort((a,b)=>a-b);const oldPct=q=>oldScores[Math.floor((oldScores.length-1)*q)]??null,oldAvg=oldScores.reduce((a,b)=>a+b,0)/Math.max(1,oldScores.length),oldBands={};for(const x of oldScores){const b=x>=90?'90_100':x>=80?'80_89':x>=70?'70_79':x>=60?'60_69':x>=50?'50_59':'below_50';oldBands[b]=(oldBands[b]||0)+1}const result={versions:{scoring_model_version:'2.0.0',business_dataset_version:'business-models-v2.0.0',country_overlay_version:'IN-2026.08-v1',financial_engine_version:'1.1.0'},original_personas:baseline,regression:{passed:pass,total:reg.length,failures:fail},stress:{persona_count:stress.length,scored_pairs:allScores.length,batch7_baseline:{average:Math.round(oldAvg*10)/10,median:oldPct(.5),p90:oldPct(.9),minimum:oldScores[0]??null,maximum:oldScores.at(-1)??null,bands:oldBands},batch8:{average:Math.round(avg*10)/10,median:pct(.5),p90:pct(.9),minimum:allScores[0]??null,maximum:allScores.at(-1)??null,bands},top_model_frequency:Object.entries(winner).sort((a,b)=>b[1]-a[1]),top3_frequency:Object.entries(top3).sort((a,b)=>b[1]-a[1]),avoid_frequency:Object.entries(avoided).sort((a,b)=>b[1]-a[1]),average_exclusions:Math.round(exclusions.reduce((a,b)=>a+b,0)/exclusions.length*10)/10}};
writeFileSync(resolve(root,'data','BATCH8_QA_RESULTS.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
