import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{normalizeAssessment,buildResult,selectTeasers,ENGINE_VERSIONS,formatCurrency,stableRank}from'../shared/escapeplan-result-engine.mjs';import{scoreV2}from'./match_engine_v2.mjs';
const root=resolve(import.meta.dirname,'..'),data=n=>JSON.parse(readFileSync(resolve(root,'data',n)));const models=data('BUSINESS_MODELS_SEED_V2.json').models,reg=data('REGRESSION_PERSONAS.json').personas;
const raw=(motivation,situation,capital,time,environment,strengths,tradeoff,extra={})=>({answerText:{motivation:[motivation],situation:[situation],capital:[capital],time:[time],environment:[environment],strengths,tradeoff:[tradeoff],...extra}});
const personas=[
 ['A',raw('I want more income','Full-time job','₹25K–₹1L','1 hour/day','Sell or build through the internet',['Selling / convincing'],'Money sooner')],
 ['B',raw('I want out of my job eventually','Full-time job','₹1L–₹3L','2–3 hours/day','Combine both',['Technology / systems','Selling / convincing'],'Balanced',{runway:['5–7 months']})],
 ['C',raw('I want to build real wealth','Ready to go full-time','₹7L+','Full-time','Run something people can visit / use locally',['Managing people / operations'],'Growth first',{operations:['Comfortable with both']})],
 ['D',raw('I want something of my own','Studying','Under ₹25K','2–3 hours/day','Sell or build through the internet',['Creative ideas / content'],'Build for the long term')],
 ['E',raw('I want to build real wealth','Already running a business','₹7L+','4–6 hours/day','Combine both',['Managing people / operations','Finding products / deals'],'Growth first',{operations:['Comfortable with both']})],
 ['F',raw('I’m just exploring','Full-time job','Under ₹25K','1 hour/day','I don’t care — show me what fits',['Nothing obvious yet'],'Balanced',{runway:['Less than 2 months']})],
 ['G',raw('I want something of my own','Ready to go full-time','₹1L–₹3L','Full-time','Run something people can visit / use locally',['Networking'],'Money sooner',{operations:['Staff is okay']})],
 ['H',raw('I want more income','Between jobs','₹1L–₹3L','2–3 hours/day','Combine both',['Nothing obvious yet'],'Balanced')]
];
assert.equal(formatCurrency(2500000),'₹25,000');assert.deepEqual(stableRank([{model:{business_model_id:'z'},score:{total:70}},{model:{business_model_id:'a'},score:{total:70}}]).map(x=>x.model.business_model_id),['a','z']);
const mapped=normalizeAssessment(personas[0][1],'mapping-test');assert.equal(mapped.employment_status,'full_time_job');assert.equal(mapped.money.safe_risk_capital_minor,2500000);assert.equal(mapped.normalization.field_classes.monthly_income_target,'C');
const ui=[];for(const [id,input]of personas){const assessment=normalizeAssessment(input,`persona-${id}`),one=buildResult(assessment,models),two=buildResult(structuredClone(assessment),models);assert.deepEqual(one.ranked_businesses.map(x=>[x.business_model_id,x.profile_match_score]),two.ranked_businesses.map(x=>[x.business_model_id,x.profile_match_score]));assert.equal(one.engine.scoring_model_version,'2.0.0');assert(one.top_business.reasons.every(x=>x.factor&&Number.isFinite(x.score)));assert(one.alternative_teasers.every(x=>one.ranked_businesses.some(r=>r.business_model_id===x.business_model_id)));assert(one.avoid_models.every(x=>x.reasons.length));ui.push({persona:id,top1:{id:one.top_business.business_model_id,name:one.top_business.name,score:one.top_business.profile_match_score},top4:one.ranked_businesses.slice(0,4).map(x=>x.business_model_id),teasers:one.alternative_teasers.map(x=>({kind:x.kind,rank:x.rank,label:x.label})),avoid:one.avoid_models.map(x=>x.business_model_id),readiness:one.readiness,reasons:one.top_business.reasons.map(x=>x.factor)});}
assert(new Set(ui.map(x=>x.top1.id)).size>=4,'Eight personas should produce at least four distinct winners');assert(ui.filter(x=>x.top1.score>=90).length<=1,'90%+ must remain rare across UI personas');
let regressionPass=0;for(const fixture of reg){const ranked=models.map(m=>({id:m.business_model_id,category:m.category,...scoreV2(fixture.assessment,m)})).filter(x=>!x.excluded).sort((a,b)=>b.total-a.total||a.id.localeCompare(b.id)),ids=ranked.map(x=>x.id),e=fixture.expectations;let ok=true;for(const id of e.top5_must_include??[])if(!ids.slice(0,5).includes(id))ok=false;for(const id of e.top10_must_exclude??[])if(ids.slice(0,10).includes(id))ok=false;if(e.top5_category_must_include&&!ranked.slice(0,5).some(x=>e.top5_category_must_include.includes(x.category)))ok=false;if(e.top10_must_not_be_all_online&&ranked.slice(0,10).every(x=>models.find(m=>m.business_model_id===x.id).online_offline_type==='online'))ok=false;if(ok)regressionPass++;}
assert.equal(regressionPass,17);console.log(JSON.stringify({versions:ENGINE_VERSIONS,persona_results:ui,distinct_winners:new Set(ui.map(x=>x.top1.id)).size,regression:{passed:regressionPass,total:reg.length}},null,2));
