(function(){'use strict';
const questions=[
{id:'motivation',stage:'Start with the change',title:'What are you trying to change right now?',help:'Choose the one that matters most today.',max:1,options:['I want more income','I want out of my job eventually','I want something of my own','I want to build real wealth','I’m just exploring']},
{id:'situation',stage:'Your life today',title:'What does your life look like today?',help:'This tells us what a realistic first move looks like.',max:1,options:['Full-time job','Studying','Already running a business','Ready to go full-time','Between jobs']},
{id:'capital',stage:'Set a safe test range',title:'If the right business appeared tomorrow, what could you comfortably test with?',help:'Not everything. Just an amount you could test without risking essential expenses.',max:1,options:['Under ₹25K','₹25K–₹1L','₹1L–₹3L','₹3L–₹7L','₹7L+']},
{id:'time',stage:'Protect your real week',title:'Be realistic — how much time can this get from you?',help:'Think about a normal week, not your most motivated one.',max:1,options:['1 hour/day','2–3 hours/day','4–6 hours/day','Full-time']},
{id:'environment',stage:'Choose your working world',title:'Which kind of work sounds more like you?',help:'Choose the operating style that feels most natural.',max:1,options:['Sell or build through the internet','Run something people can visit / use locally','Combine both','I don’t care — show me what fits']},
{id:'strengths',stage:'Find your unfair advantages',title:'What do people already rely on you for?',help:'Choose up to two. Existing advantages can change what is realistic.',max:2,options:['Selling / convincing','Technology / systems','Creative ideas / content','Finding products / deals','Managing people / operations','Networking','Numbers / analysis','Nothing obvious yet']},
{id:'tradeoff',stage:'Make the final trade-off',title:'Which outcome matters more to you right now?',help:'Choose where you sit between speed and long-term scale.',max:1,options:['Money sooner','Balanced','Growth first','Build for the long term']}];
const insights={1:{type:'stage',title:'Goal found.',copy:'Now we can test what fits your resources—not somebody else’s life.'},2:{type:'capital',title:'Your safe test range is set.',copy:'Some routes just became less practical. Others moved closer.'},4:{type:'dna',title:'Your business DNA is taking shape.',copy:'We can now see how your money, time and preferred working world interact.'},5:{type:'strengths',title:'Your advantage changes the map.',copy:'Two people with the same budget can need completely different businesses.'}};
const conditionalQuestions={runway:{id:'runway',stage:'One more detail for a safer route',title:'If your salary stopped tomorrow, how long would your savings last?',help:'A rough answer is enough.',max:1,options:['Less than 2 months','2–4 months','5–7 months','8–12 months','1 year+']},operations:{id:'operations',stage:'One more detail for a local route',title:'How do you feel about staff and inventory?',help:'This can materially change which local models stay realistic.',max:1,options:['Avoid both','Inventory is okay','Staff is okay','Comfortable with both']}};
const key='escapeplan-assessment-v1',state=load(),categoryLabel={service:'Services',b2b:'B2B services',commerce:'Commerce',software:'Software',digital:'Digital',content:'Content',market:'Platforms',rental:'Rental',food:'Food',retail:'Retail'};let routeModels=[],routeFeedback=null;
fetch('/data/BUSINESS_MODELS_SEED_V2.json').then(r=>r.ok?r.json():Promise.reject()).then(data=>{routeModels=data.models||[];map()}).catch(()=>{});
const $=id=>document.getElementById(id),n={main:$('assessment'),intro:$('intro-view'),quiz:$('quiz-view'),introCount:$('intro-count'),introTitle:$('intro-title'),introCopy:$('intro-copy'),introButton:$('intro-button-label'),question:$('question-view'),insight:$('insight-view'),category:$('question-category'),title:$('question-title'),help:$('question-help'),visual:$('question-visual'),options:$('option-list'),route:$('route-field'),routeStatus:$('route-status'),actions:$('assessment-actions'),continue:$('continue-button'),continueLabel:document.querySelector('#continue-button span:first-child'),back:document.querySelector('[data-action="back"]'),reaction:$('reaction'),reactionTitle:$('reaction-title'),reactionCopy:$('reaction-copy'),insightTitle:$('insight-title'),insightCopy:$('insight-copy'),insightVisual:$('insight-visual')};
const icons={motivation:['M5 13h4l2-7 3 14 2-7h4','M6 5h12v5a6 6 0 0 1-12 0z M9 20h6 M12 16v4','M4 12 12 5l8 7v8h-6v-5h-4v5H4z','M5 18 10 13l3 3 6-8 M15 8h4v4','M12 3a9 9 0 1 0 9 9'],strengths:['M4 14l5-5 4 4 7-7','M5 5h6v6H5z M13 13h6v6h-6z M15 5h4v4h-4z M5 15h4v4H5z','M12 3l2.3 4.7 5.2.8-3.8 3.7.9 5.3-4.6-2.5L7.4 20l.9-5.3-3.8-3.7 5.2-.8z','M4 8h16v10H4z M8 8V5h8v3','M4 18V8l8-5 8 5v10 M8 18v-5h8v5','M5 12h14 M12 5v14','M5 18l4-5 3 2 7-9','M7 7l10 10 M17 7 7 17']},svg=p=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${p}"/></svg>`;
function load(){try{const x=JSON.parse(sessionStorage.getItem(key)||localStorage.getItem(key));return x&&typeof x==='object'?{index:0,mode:'core',followupIndex:0,followupIds:[],answers:{},answerText:{},insightAfter:null,introComplete:false,introStep:0,...x}:{index:0,mode:'core',followupIndex:0,followupIds:[],answers:{},answerText:{},insightAfter:null,introComplete:false,introStep:0};}catch(_){return{index:0,mode:'core',followupIndex:0,followupIds:[],answers:{},answerText:{},insightAfter:null,introComplete:false,introStep:0};}}
function save(){const x=JSON.stringify(state);sessionStorage.setItem(key,x);localStorage.setItem(key,x)}function selected(id){return Array.isArray(state.answers[id])?state.answers[id]:[]}function active(){return state.mode==='followup'?conditionalQuestions[state.followupIds[state.followupIndex]]:questions[state.index]}function queue(){const q=[];if(selected('situation').includes(0))q.push('runway');if(selected('environment').includes(1))q.push('operations');return q}function stage(id){return EscapePlanAssessmentLogic.progressStage(id)}
function intro(){const steps=[['A clearer way to choose','There are hundreds of businesses you could start.','The useful question is not “Which one looks exciting?” It is “Which few actually fit your life?”','Show me how'],['Your constraints are clues','Most business ideas are wrong for you.','Your money, time, working style and strengths can remove the noise—before you risk months or lakhs.','See the map'],['Your route begins here','We’ll narrow the field as you answer.','Watch your Escape Route Map react. We will only reveal your strongest matches after the assessment.','Start my EscapePlan']],s=steps[state.introStep]||steps[0];n.introCount.textContent=s[0];n.introTitle.textContent=s[1];n.introCopy.textContent=s[2];n.introButton.textContent=s[3];n.intro.dataset.step=state.introStep;n.intro.hidden=false;n.quiz.hidden=true;n.actions.hidden=true;n.main.focus({preventScroll:true})}
function start(){state.introComplete=true;save();n.intro.hidden=true;n.quiz.hidden=false;render()}function stages(s){const o=['GOAL','MONEY','STYLE','FIT'],c=o.indexOf(s);document.querySelectorAll('[data-stage]').forEach(x=>{const i=o.indexOf(x.dataset.stage);x.classList.toggle('is-active',i===c);x.classList.toggle('is-done',i<c);x.textContent=i<c?`✓ ${o[i]}`:i===c?`● ${o[i]}`:`○ ${o[i]}`})}
function routeState(){
 if(!routeModels.length)return{count:null,categories:[],scores:{}};
 const cap=[0,2500000,10000000,30000000,70000000][selected('capital')[0]],hours=[1,2,4,8][selected('time')[0]],env=['online','offline','hybrid','no_preference'][selected('environment')[0]],strengths=selected('strengths'),trade=selected('tradeoff')[0],motivation=selected('motivation')[0],situation=selected('situation')[0],ops=selected('operations')[0];
 const eligible=routeModels.filter(model=>{const validation=model.validation_capital||{},minimum=validation.minimum_cash_required_minor??model.capital.minimum_test_minor;if(cap!==undefined&&cap<minimum&&!validation.zero_cost_validation_supported&&!validation.concept_validation_possible_without_launch)return false;if(ops===0&&model.requires_inventory)return false;return true}),scores={};
 for(const model of eligible){
  const s=model.scores;let fit=1;
  if(cap!==undefined){const minimum=model.validation_capital?.minimum_cash_required_minor??model.capital.minimum_test_minor;fit+=(cap>=model.capital.typical_startup_low_minor)?0.35:0.12;fit+=(cap>=minimum)?0.22:-0.25}
  if(hours!==undefined)fit+=(hours>=model.ideal_daily_hours_range[0])?0.35:-0.28;
  if(hours<=2&&model.can_start_part_time)fit+=.2;
  if(env&&env!=='no_preference')fit+=(model.online_offline_type===env)?0.5:((model.online_offline_type==='hybrid'||env==='hybrid')?0.2:-0.18);
  const deps={0:'sales_dependency',1:'technical_complexity',2:'creative_dependency',3:'product_dependency',4:'operations_dependency',5:'customer_interaction',6:'business_experience_requirement'};
  for(const strength of strengths)if(deps[strength])fit+=(s[deps[strength]]-5)/18;
  if(trade===0)fit+=(s.speed_to_first_revenue-5)/16;if(trade>=2)fit+=(s.scalability-5)/16;if(motivation===0)fit+=(s.side_hustle_compatibility+s.speed_to_first_revenue-10)/28;if(motivation===3)fit+=(s.scalability+s.income_ceiling-10)/25;if(situation===0)fit+=(s.side_hustle_compatibility-s.full_time_founder_requirement)/22;
  const category=categoryLabel[model.category]||model.category;scores[category]=(scores[category]||[]).concat(fit)
 }
 const categories=Object.entries(scores).map(([name,values])=>({name,score:values.reduce((a,b)=>a+b,0)/values.length})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name));return{count:eligible.length,categories,scores:Object.fromEntries(categories.map(x=>[x.name,x.score]))}
}
function map(){const current=routeState(),stageName=stage(active()?.id),head={GOAL:'Understanding what you want',MONEY:'Checking what fits your budget',STYLE:'Matching how you naturally work',FIT:'Separating your strongest paths'}[stageName];n.routeStatus.textContent=head;const previous=routeFeedback?.previous,delta=previous&&current.count!=null?current.count-previous.count:null,changed=routeFeedback?.questionId,rows=current.categories.slice(0,3).map((item,index)=>{const before=previous?.scores?.[item.name],direction=before==null?'':item.score>before+.04?'↑':item.score<before-.04?'↓':'→';return`<li style="--order:${index}"><span>${item.name}</span><b class="route-direction route-direction--${direction==='↓'?'down':'up'}">${direction}</b></li>`}).join('');const count=current.count==null?'Many':current.count,countLabel=current.count==null?'paths open':'paths being compared',deltaCopy=delta?`${delta>0?'+':''}${delta} after your ${changed||'last'} choice`:changed?'Priorities updated from your answer':'Your answers will narrow this live';n.route.innerHTML=`<div class="route-summary"><strong><span>${count}</span><small>${countLabel}</small></strong><em class="${delta<0?'is-narrowing':''}">${deltaCopy}</em></div><ul class="route-categories">${rows||'<li><span>Broad directions</span><b>Open</b></li>'}</ul><p>${Math.max(0,current.categories.length-3)} other ${current.categories.length-3===1?'direction':'directions'} being compared</p>`;const card=n.route.closest('.route-map');card?.classList.remove('is-updating');if(changed)requestAnimationFrame(()=>{card?.classList.add('is-updating');setTimeout(()=>card?.classList.remove('is-updating'),650)});routeFeedback={previous:current,questionId:null}}
function visual(q,s){const p=s[0];if(q.id==='capital')return`<div class="capital-meter">${q.options.map((o,i)=>`<i class="${p!==undefined&&i<=p?'is-filled':''}" style="--h:${34+i*11}px"></i>`).join('')}</div><span>Lean test</span><span>More operating room</span>`;if(q.id==='time')return`<div class="time-dial" style="--turn:${p===undefined?0:(p+1)*38}deg"><i></i><b>${p===undefined?'Your week':q.options[p]}</b></div>`;if(q.id==='environment')return`<div class="work-scenes"><span class="${p===0||p===2?'is-on':''}">${svg('M4 5h16v11H4z M9 20h6 M12 16v4')}</span><i></i><span class="${p===1||p===2?'is-on':''}">${svg('M4 10h16v10H4z M3 10l2-6h14l2 6 M8 14h3v6')}</span></div>`;if(q.id==='strengths')return`<div class="token-count"><span>Choose up to 2</span><div aria-label="${s.length} of 2 advantages selected"><i class="${s.length>0?'is-filled':''}"></i><i class="${s.length>1?'is-filled':''}"></i></div><b>${s.length} / 2 selected</b></div>`;if(q.id==='tradeoff')return`<div class="tradeoff-balance"><span>Proof sooner</span><i><b style="--position:${p===undefined?50:p/3*100}%"></b></i><span>Scale later</span></div>`;return''}
function options(q,s){return q.options.map((o,i)=>{const a=s.includes(i),ic=(icons[q.id]||[])[i];return`<button class="option-card${a?' is-selected':''}" type="button" data-option="${i}" aria-pressed="${a}">${ic?`<span class="option-icon">${svg(ic)}</span>`:'<span class="option-indicator" aria-hidden="true"></span>'}<span class="option-label">${o}</span></button>`}).join('')}
function render(){const q=active(),s=selected(q.id);n.intro.hidden=true;n.quiz.hidden=false;n.quiz.dataset.question=q.id;stages(stage(q.id));map();n.category.textContent=q.stage;n.title.textContent=q.title;n.help.textContent=q.help;n.visual.innerHTML=visual(q,s);n.visual.hidden=!n.visual.innerHTML;n.options.className=`option-list option-list--${q.id}`;n.options.setAttribute('aria-label',q.max>1?`Choose up to ${q.max}`:'Choose one');n.options.innerHTML=options(q,s);n.continue.disabled=!s.length;n.continue.setAttribute('aria-disabled',String(!s.length));const f=state.mode==='followup'&&state.followupIndex===state.followupIds.length-1,l=state.mode==='core'&&state.index===questions.length-1&&!queue().length;n.continueLabel.textContent=f||l?'Build My EscapePlan':'Continue';n.back.disabled=state.mode==='core'&&state.index===0;n.question.hidden=false;n.insight.hidden=true;n.actions.hidden=false;n.reaction.hidden=true;n.main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}
async function choose(i){const q=active(),s=selected(q.id),before=routeState();if(q.max===1)state.answers[q.id]=[i];else if(s.includes(i))state.answers[q.id]=s.filter(v=>v!==i);else if(s.length<q.max)state.answers[q.id]=[...s,i];else state.answers[q.id]=[s[1],i];state.answerText[q.id]=EscapePlanAssessmentLogic.answerLabels(q,state.answers);routeFeedback={previous:before,questionId:{capital:'budget',time:'time',environment:'working-style',strengths:'strength',tradeoff:'speed'}[q.id]||q.id};save();render();const request={user_state:state.answerText,question_id:q.id},version=JSON.stringify(state.answers[q.id]),fallback=await AssessmentNarrator.fallback(request);n.reactionTitle.textContent=fallback.reaction;n.reactionCopy.textContent=fallback.supporting_copy;n.reaction.hidden=false;const generated=await AssessmentNarrator.narrate(request);if(JSON.stringify(state.answers[q.id])===version&&generated.meta?.narrator_mode==='AI'&&generated.elapsed_ms<600){n.reactionTitle.textContent=generated.reaction;n.reactionCopy.textContent=generated.supporting_copy}document.dispatchEvent(new CustomEvent('escapeplan:narration',{detail:generated.meta||{narrator_mode:'DETERMINISTIC_FALLBACK'}}))}
function insightVisual(type){const top=routeState().categories.slice(0,3).map(x=>x.name),strengths=state.answerText.strengths||[];if(type==='stage')return'<div class="meaning-route"><span>WHAT YOU WANT</span><i></i><b>REALISTIC FIT</b></div>';if(type==='capital')return'<div class="constraint-routes"><span></span><span></span><span></span><b>BUDGET CHECKED</b></div>';if(type==='strengths')return`<div class="advantage-merge"><span>${strengths[0]||'YOUR STRENGTH'}</span>${strengths[1]?`<i>+</i><span>${strengths[1]}</span>`:''}<b>COMBINATION ADDED</b></div>`;return`<div class="direction-stack">${top.map(x=>`<span>${x}</span>`).join('')}<b>DIRECTIONS FORMING</b></div>`}
function insight(after){const x=insights[after];if(!x)return false;state.insightAfter=after;save();n.insightTitle.textContent=x.title;n.insightCopy.textContent=x.copy;n.insightVisual.className=`insight-visual insight-visual--${x.type}`;n.insightVisual.innerHTML=insightVisual(x.type);const button=n.insight.querySelector('.insight-continue'),labels={1:'See What Changed',2:'Keep Narrowing',4:'Keep Narrowing',5:'Use My Advantages'};button.innerHTML=`${labels[after]||'Continue'} <span aria-hidden="true">→</span>`;n.question.hidden=true;n.insight.hidden=false;n.actions.hidden=true;n.main.focus({preventScroll:true});return true}
function final(){state.insightAfter='final';save();const top=routeState().categories.slice(0,4).map(x=>x.name);n.insightTitle.textContent='That’s enough.';n.insightCopy.textContent='We know what you want, what you can test and how you naturally operate.';n.insightVisual.className='insight-visual insight-visual--final';n.insightVisual.innerHTML=`<div class="route-convergence">${top.map(x=>`<span>${x}</span>`).join('')}<i></i><b>YOUR SHORTLIST&nbsp; ✓</b></div>`;n.insight.querySelector('.insight-continue').innerHTML='Build My EscapePlan <span aria-hidden="true">→</span>';n.question.hidden=true;n.insight.hidden=false;n.actions.hidden=true;n.main.focus({preventScroll:true})}
function next(){const q=active();if(!selected(q.id).length)return;if(state.mode==='followup'){if(state.followupIndex<state.followupIds.length-1){state.followupIndex++;save();render()}else final();return}if(insight(state.index))return;if(state.index===questions.length-1){state.followupIds=queue();if(state.followupIds.length){state.mode='followup';state.followupIndex=0;save();render()}else final();return}state.index++;save();render()}
function after(){const done=state.insightAfter==='final';state.insightAfter=null;if(done){save();location.href='/analysis-v2/code';return}state.index++;save();render()}function back(){if(state.mode==='followup'){if(state.followupIndex>0)state.followupIndex--;else{state.mode='core';state.index=questions.length-1}state.insightAfter=null;save();render();return}if(!state.index)return;state.index--;state.insightAfter=null;save();render()}
document.addEventListener('click',e=>{const o=e.target.closest('[data-option]');if(o){choose(Number(o.dataset.option));return}const a=e.target.closest('[data-action]')?.dataset.action;if(a==='intro-next'){if(state.introStep<2){state.introStep++;save();intro()}else start()}if(a==='intro-skip')start();if(a==='continue')next();if(a==='back')back();if(a==='exit')location.href='/';if(a==='insight-continue')after()});
if(!state.introComplete&&!Object.keys(state.answers).length)intro();else if(state.insightAfter==='final'){n.intro.hidden=true;n.quiz.hidden=false;map();final()}else if(state.insightAfter!==null&&insights[state.insightAfter]){n.intro.hidden=true;n.quiz.hidden=false;map();insight(state.insightAfter)}else start();
}());
